services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "host"
    user: root
    volumes:
      - ./Suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - ./Suricata/rules:/var/lib/suricata/rules
      - ./logs:/var/log/suricata
      - ./Suricata/update_rules.sh:/update_rules.sh  # Script di aggiornamento regole
    entrypoint: ["/bin/sh", "-c", "suricata -c /etc/suricata/suricata.yaml -i wlan0"]
    restart: unless-stopped

  zeek:
    image: zeek/zeek:latest
    container_name: zeek
    network_mode: "host"
    volumes:
      - ./zeek_logs:/opt/zeek/logs
    depends_on:
      - suricata
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: unless-stopped

volumes:
  esdata: